version: '3'
services:
  neo4j:
    image: "neo4j:3.5"
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,horus.*"
      NEO4J_dbms_memory_heap_maxsize: "8G"
      NEO4J_dbms_jvm_additional: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=3637 -Dcom.sun.management.jmxremote.rmi.port=3637 -Djava.rmi.server.hostname=<EXTERNAL_IP_ADDRESS>"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4JLABS_PLUGINS: "[\"apoc\"]"
    volumes:
    - ./neo4j/logs:/logs
    - ./neo4j/data:/data
    - ./neo4j/plugins:/var/lib/neo4j/plugins
    ports:
    - "7474:7474"
    - "7473:7473"
    - "7687:7687"
    - "3637:3637"
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
    - ./zk/data:/var/lib/zookeeper/data
    - ./zk/logs:/var/lib/zookeeper/logs
  kafka:
    image: confluentinc/cp-kafka:5.4.2
    ports:
    - "9092:9092"
    - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:29092, EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092, EXTERNAL://<EXTERNAL_HOSTNAME>:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: "<EXTERNAL_IP_ADDRESS>"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka/data:/var/lib/kafka/data
  processor:
    image: fntneves/horus-processor
    volumes:
    - ./processor/conf:/conf
    - ./processor/logs:/logs
    - ./wait-for-it.sh:/usr/local/bin/wait-for-it
    depends_on:
    - neo4j
    - kafka
    ports:
    - "9010:9010"
    command: ["wait-for-it", "-t", "0", "neo4j:7687", "--", "java", "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.port=9010", "-Dcom.sun.management.jmxremote.local.only=false",  "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.rmi.port=9010",  "-jar", "horus-consumer-1.0-SNAPSHOT.jar"]
networks:
  default:
    external:
      name: horus_network
